<!-- add.phtml -->
<!-- Juan Guzmán -->

<!-- CDN's -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/extjs/6.0.0/classic/theme-neptune-touch/resources/theme-neptune-touch-all.css">
<script type = "text/javascript" src = "js/ext-all.js"></script>
<link rel="stylesheet" href="css/bootstrap.css">
<!-- / CDN's -->

<!-- Add Product -->
<div>
	<h1 class="display-2 text-center">Let's Work! <br>
	<small>Ethan, if you hate the spanish, this tool is perfect for you</small>
    </h1>
	<br>
</div>
<form action="/processadd" method="post" id="ext-content">
	

</form>
<script type = "text/javascript" src="js/ext-build-add.js"></script>
<!-- / Add Product -->