<!-- delete.phtml -->
<!-- Juan Guzmán -->

<!-- CDN's -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/extjs/6.0.0/classic/theme-neptune-touch/resources/theme-neptune-touch-all.css">
<script type = "text/javascript" src = "js/ext-all.js"></script>
<!-- / CDN's -->

<!-- Add Product -->
<div>
	<h1 class="display-2 text-center">Stop, bro! <br>
	<small>Ethan, take this tool with care, I wait you enjoy it!</small>
    </h1>
	<br>
</div>
<form action="/processdel" method="post" id="ext-content">
	
</form>
<script type = "text/javascript" src="js/ext-build-delete.js"></script>
<!-- / Add Product -->