<!-- edit.phtml -->
<!-- Juan Guzmán -->

<!-- CDN's -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/extjs/6.0.0/classic/theme-neptune-touch/resources/theme-neptune-touch-all.css">
<script type = "text/javascript" src = "js/ext-all.js"></script>
<!-- / CDN's -->

<!-- Add Product -->
<div>
	<h1 class="display-2 text-center">You´re Great! <br>
	<small>Ethan, Is a pleasure to have you here</small>
    </h1>
	<br>
</div>
<form action="/processedit" method="post" id="ext-content">
	
</form>
<script type = "text/javascript" src="js/ext-build-edit.js"></script>
<!-- / Add Product -->