<!-- index.phtml -->
<!-- Juan Guzmán -->

<!-- CDN's -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/extjs/6.0.0/classic/theme-neptune-touch/resources/theme-neptune-touch-all.css">
<script type = "text/javascript" src = "js/ext-all.js"></script>
<!-- / CDN's -->

<!-- Menu Container -->
  <div class="container">
     <h1 class="display-2 text-center">Welcome Ethan!</h1>
        <br>
            <p class="text-center">We´re Glad to have you here and help you in your work, that's <br>
            keep <em>IMF's</em> Inventory actualized, so, I create this app for you <br>
            I will wait that you enjoy it! <br>
            <br>
            <br>
            <small>Juan Guzmán <br>
            <em>Future Alegra Dev</em>
            </small>
            </p>       
  </div>
  <div id="ext-content"></div>
  <script type = "text/javascript" src="js/ext-build.js"></script>
<!-- / Menu Container -->